clone_depth: 1

install:
    - cd c:\

    # Install Boost libraries
    - appveyor-retry nuget install boost_atomic-vc120 -Version 1.61.0
    - appveyor-retry nuget install boost_system-vc120 -Version 1.61.0
    - appveyor-retry nuget install boost_filesystem-vc120 -Version 1.61.0
    - appveyor-retry nuget install boost_date_time-vc120 -Version 1.61.0
    - appveyor-retry nuget install boost_thread-vc120 -Version 1.61.0

    # Install libiio
    - appveyor DownloadFile https://ci.appveyor.com/api/projects/analogdevicesinc/libiio/artifacts/libiio.zip?branch=master
    - 7z x libiio*.zip > nul
    - mkdir libiio-win64
    - mv libiio-*/MS64/* libiio-win64/
    - mv libiio-*/include/* libiio-win64/

    # Install libad9361
    - appveyor DownloadFile https://ci.appveyor.com/api/projects/analogdevicesinc/libad9361-iio/artifacts/libad9361-win64.zip?branch=master
    - 7z x libad9361-win64.zip > nul

    # Install SWIG
    - appveyor DownloadFile https://sourceforge.net/projects/swig/files/swigwin/swigwin-3.0.8/swigwin-3.0.8.zip
    - 7z x swigwin-3.0.8.zip > nul

    # Install Flex / Bison
    - appveyor DownloadFile https://sourceforge.net/projects/winflexbison/files/old_versions/win_flex_bison-2.5.6.zip
    - 7z x win_flex_bison-2.5.6.zip > nul

    # Install libvolk
    - cd "c:\Program Files"
    - appveyor DownloadFile https://ci.appveyor.com/api/projects/analogdevicesinc/volk/artifacts/libvolk-x64.zip?branch=master
    - 7z x libvolk-x64.zip > nul

    # Install GNU Radio
    - appveyor DownloadFile https://ci.appveyor.com/api/projects/analogdevicesinc/gnuradio/artifacts/gnuradio-x64.zip?branch=maint-windows
    - 7z x gnuradio-x64.zip > nul

build_script:
    - mkdir c:\projects\gr-iio\build
    - cd c:\projects\gr-iio\build

    # Without this directory in the %PATH%, compiler tests fail because of missing DLLs
    - set PATH=%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin

    - cmake -G "Visual Studio 12 Win64" \
        -DCMAKE_INSTALL_PREFIX:PATH="c:/Program Files/gnuradio" \
        -DCMAKE_BUILD_TYPE:STRING=Release \
        -DBoost_INCLUDE_DIR:PATH=c:/boost.1.61.0.0/lib/native/include \
        -DBoost_ATOMIC_LIBRARY_RELEASE:FILEPATH=c:/boost_atomic-vc120.1.61.0.0/lib/native/address-model-64/lib/boost_atomic-vc120-mt-1_61.lib \
        -DBoost_FILESYSTEM_LIBRARY_RELEASE:FILEPATH=c:/boost_filesystem-vc120.1.61.0.0/lib/native/address-model-64/lib/boost_filesystem-vc120-mt-1_61.lib \
        -DBoost_THREAD_LIBRARY_RELEASE:FILEPATH=c:/boost_thread-vc120.1.61.0.0/lib/native/address-model-64/lib/boost_thread-vc120-mt-1_61.lib \
        -DBoost_SYSTEM_LIBRARY_RELEASE:FILEPATH=c:/boost_system-vc120.1.61.0.0/lib/native/address-model-64/lib/boost_system-vc120-mt-1_61.lib \
        -DBoost_LIBRARY_DIR_RELEASE:PATH=c:/boost_date_time-vc120.1.61.0.0/lib/native/address-model-64/lib;c:/boost_thread-vc120.1.61.0.0/lib/native/address-model-64/lib;c:/boost_system-vc120.1.61.0.0/lib/native/address-model-64/lib;c:/boost_filesystem-vc120.1.61.0.0/lib/native/address-model-64/lib \
        -DSWIG_EXECUTABLE:FILEPATH=c:/swigwin-3.0.8/swig.exe \
        -DIIO_INCLUDE_DIRS:PATH=c:/libiio-win64 \
        -DIIO_LIBRARIES:FILEPATH=c:/libiio-win64/libiio.lib \
        -DFLEX_EXECUTABLE:FILEPATH=c:/win_flex.exe \
        -DBISON_EXECUTABLE:FILEPATH=c:/win_bison.exe \
        -DAD9361_INCLUDE_DIRS:PATH=c:/libad9361-win64 \
        -DAD9361_LIBRARIES:FILEPATH=c:/libad9361-win64/libad9361.lib \
        -DGnuradio_DIR:PATH="c:/Program Files/gnuradio/lib/cmake/gnuradio" \
        -DCPPUNIT_INCLUDE_DIRS:PATH=c:/ \
        ..

    - cmake --build . --config Release --target INSTALL

    # Create an archive
    - cd "c:\Program Files"
    - 7z a "c:\gnuradio-x64.zip" gnuradio
    - appveyor PushArtifact c:\gnuradio-x64.zip
